Update BuildConfig.groovy
I still have several issue using this plugin in combination with redis plugin. there are runtime problem, mostly due to differnt jedis library I suppose.

I hope that bumping tomcat-redis-session library from 0.5 to 0.6 will fix that.

this si my stacktrace: java.lang.RuntimeException: java.lang.NoSuchMethodError: redis.clients.jedis.Transaction.sadd(Ljava/lang/String;Ljava/lang/String;)Lredis/clients/jedis/Response;